### PR TITLE
1.15

### PR DESCRIPTION
**Pull request by AlmightyAnubis**
Hi Geek,

I just downloaded your Code to make some experiments to show stuff on screen. While  my experiments I implemented an extension for entitys. Because the main part is yours, I don't want to publish it under my name, but it would be sad, if it wouldn't published. If you want, i will send you the code.

best regards
Anubis

### CODE REVIEW

**Comment by Tom-The-Geek** [comment]
This sounds interesting, I would certainly like to take a look.

Tom_The_Geek

**Comment by AlmightyAnubis** [comment]
I am new to GitHub. Can I send you the code directly or do I need your E-mail?

Ps: I am from Germany. I hope my English is not to worse

**Comment by AlmightyAnubis** [comment]
I uploaded it private an invited you. I hope this was the right way to do it

**Comment by Tom-The-Geek** [comment]
This code looks interesting and I will have a good look at it tomorrow.

**Comment by AlmightyAnubis** [comment]
I copied your way of presenting, added a drop Item via Loot-Table(like gunpowder for creeper, but for some mobs it goes wrong. blazes don't show the blaze rod, but i couldn't figure out why)  and a spawn-item(mostly spawn-egg). Additionally there is a health presentation. When it has over 20 health(I tested with Iron-Golem and horse), it shows as bar and numbers, for less, it shows the hearts (most mobs have less the 20 hearts. i tested with pig, zombie, creeper...). The window automatically adjusts, although the way of coding the adjustment wasn't the most beautiful one.

And while testing, I found, maybe you can call it bug. Because, you only trigger when changing the watching direction, the display don't adjust, when you walk without moving the camera or when the block or entity moves out of the way. But I can't find a way of changing that, because I don't know all the events, that trigger.

**Comment by AlmightyAnubis** [comment]
Why did you close and what do you think? Will you add this to your code?

**Comment by Tom-The-Geek** [comment]
A. Closed because I don't want to merge the 1.15 branch to master as that is what this PR would do.

B. I may use some code from your project to build support for entities when I improve the way that data is sent from the server.

**Comment by AlmightyAnubis** [comment]
Ok, thanks for the answer

**Pull request closed without merging**
